apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}"},"finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"clinica-api-deployment"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}},"manager":"GoogleCloudConsole","operation":"Update","time":"2024-01-05T07:39:34Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:finalizers":{".":{},"v:\"service.kubernetes.io/load-balancer-cleanup\"":{}}},"f:status":{"f:loadBalancer":{"f:ingress":{}}}},"manager":"cloud-controller-manager","operation":"Update","subresource":"status","time":"2024-01-05T07:40:07Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:gcb-build-id":{},"f:gcb-trigger-id":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2024-01-05T08:11:27Z"}],"name":"clinica-api-deployment-service","namespace":"default"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"34.118.238.66","clusterIPs":["34.118.238.66"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":32175,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"clinica-api-deployment"},"sessionAffinity":"None","type":"LoadBalancer"}}
  creationTimestamp: "2024-01-07T18:21:31Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: clinica-api-deployment
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cloud.google.com/neg: {}
          f:gcb-build-id: {}
          f:gcb-trigger-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        f:allocateLoadBalancerNodePorts: {}
        f:clusterIP: {}
        f:clusterIPs: {}
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ipFamilies: {}
        f:ipFamilyPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-01-07T18:21:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: cloud-controller-manager
    operation: Update
    subresource: status
    time: "2024-01-07T18:22:03Z"
  name: clinica-api-deployment-service
  namespace: default
  resourceVersion: "89904"
  uid: 7a8bc6ce-cdd7-4e63-bb21-70d7e8a29ecb
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.238.66
  clusterIPs:
  - 34.118.238.66
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32175
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: clinica-api-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.68.33.222
