apiVersion: v1
kind: Deployment
metadata:
  name: clinica-api-deployment
spec:
  selector:
    matchLabels:
      app: clinica-api
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: clinica-api
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
